# =============================================================================
#  models.psd1 — THE single source of truth for model selection.
#
#  Both the downloader (scripts/fetch-models.ps1) and the runtime config
#  (config/llama-swap.yaml, GENERATED by scripts/gen-llama-swap.ps1) derive
#  from this file. Edit here once; both follow.
#
#  Loaded with Import-PowerShellDataFile (data-only / safe — no code runs).
#
#  ── CHANGING MODELS / VRAM ──────────────────────────────────────────────────
#  Low on VRAM? Set `activeProfile = '12gb'` below BEFORE running setup, or later:
#      llm profile 12gb           (persists + regenerates the runtime config)
#      setup.bat -Profile 12gb    (at setup time)
#  Peek a profile without switching or downloading:
#      llm fetch --list 12gb      (dry-run; lists files + sizes, pulls nothing)
#
#  Profiles available: '16gb' (default), '12gb'.  Footprints: see _targetVRAM below.
#  (Add '32gb'/'64gb' later the same way — copy a profile block, bump the models/quants.)
#
#  ── SCHEMA (per model) ──────────────────────────────────────────────────────
#    repo / path  : HuggingFace repo + file path  → download URL
#    gguf         : local filename in models/      → also the -m path at runtime
#    ctx          : context window (-c). Omit for embeddings.
#    sizeGB       : approx on-disk size (display + dry-run totals only)
#    kv=$true     : apply the KV-cache quant macro (${kv}). Big models only — small
#                   pinned models (fim/embed) skip it (negligible KV at their size).
#    flags        : extra llama-server flags (array). Appended last, so they can
#                   OVERRIDE the srv-macro defaults (e.g. @('-ngl','30') for low VRAM).
#    setParams    : server-side sampling enforcement → llama-swap filters.setParams
#    ttl=0        : never auto-unload (pinning)
#    pinned=$true : keep resident — excluded from the swap group (see `group`)
#    embedding    : adds --embedding, omits the KV-quant flags
#  Keys starting with '_' (e.g. _targetVRAM) are METADATA, not models — skipped
#  by the generator and the downloader.
#
#  All repo/path URLs below verified live on huggingface.co (HTTP 200) on 2026-06-24.
#  If you CHANGE a repo/path, re-check it — quant filenames vary by uploader and casing
#  matters. Quick check:  llm fetch --list <profile>  then HEAD the resolve URLs.
# =============================================================================
@{
  # The active profile. '$env:LLM_PROFILE' (if set) overrides this for one
  # invocation without rewriting the file.
  activeProfile = '16gb'

  # Tunable knobs. Values here are the defaults; copy config/user.psd1.example to
  # config/user.psd1 (gitignored) to override any of these without touching git-tracked files.
  # Re-run `llm gen` after editing user.psd1. Changes take effect on next `llm serve`.
  defaults = @{
    ngl         = 99                # GPU layers. Lower (e.g. 80) to CPU-offload if OOM.
    flashAttn   = $true             # Required for KV-cache quant. Set false for CPU-only.
    kvQuant     = 'q8_0'            # KV cache quant. 'q4_0' = ~50% less KV VRAM. '' = disabled (Gemma).
    threads     = -1                # CPU threads for BLAS/prompt. -1 = auto.
    batch       = 512               # Logical batch size (-b). Higher = faster prefill. Max 2048.
    parallel    = 1                 # Parallel request slots (-np). >1 for multi-user setups.
    port        = 8080              # llama-swap API endpoint port.
    webuiPort   = 3000              # Open WebUI port.
    maxTokens   = 512               # Default max_tokens for `llm chat`.
    webuiSecret = 'local-llm-dev'   # Change before exposing WebUI on LAN.
  }

  # llama-server command pieces — values generated by gen-llama-swap.ps1 from defaults above.
  # Do not edit these; they are overwritten at every `llm gen` / `llm serve`.
  macros = @{
    srv = ''   # Generated. Do not edit.
    kv  = ''   # Generated. Do not edit.
  }

  # Swap policy. members = ROLE names that share VRAM (only one resident at a time;
  # loading one evicts the others). Pinned models (fim/embed) are NOT listed here —
  # their ttl:0 keeps them alongside whichever big model is active.
  group = @{ name = 'ondemand'; swap = $true; members = @('planner', 'coder', 'chat') }

  profiles = @{

    # Verified set. Runs on a 16GB card (RTX 5080): one big model resident at a
    # time; the 30B-A3B planner uses light RAM offload (fast — only 3B active).
    '16gb' = @{
      _targetVRAM = '16GB+ (tested RTX 5080; 30B planner uses light RAM offload)'
      planner = @{ repo = 'Qwen/Qwen3-30B-A3B-GGUF';                   path = 'Qwen3-30B-A3B-Q4_K_M.gguf';             gguf = 'qwen3-30b-a3b-q4.gguf';      ctx = 16384; kv = $true; sizeGB = 17.3; flags = @('--temp', '0.3') }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-14B-Instruct-GGUF'; path = 'Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf'; gguf = 'qwen-coder-14b-q4_k_m.gguf'; ctx = 16384; kv = $true; sizeGB = 8.4 }
      chat    = @{ repo = 'Qwen/Qwen3-14B-GGUF';                       path = 'Qwen3-14B-Q4_K_M.gguf';                 gguf = 'qwen3-14b-q4_k_m.gguf';      ctx = 16384; kv = $true; sizeGB = 8.4; setParams = @{ temperature = 0.7; top_p = 0.9 } }
      fim     = @{ repo = 'Qwen/Qwen2.5-Coder-3B-Instruct-GGUF';       path = 'qwen2.5-coder-3b-instruct-q8_0.gguf';   gguf = 'qwen-coder-3b-q8_0.gguf';    ctx = 8192;  sizeGB = 3.4; ttl = 0; pinned = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                      path = 'bge-m3-Q8_0.gguf';                      gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true }
    }

    # Tight fit for ~8GB cards (RTX 3070, 4060, etc.). One big model at a time alongside
    # pinned fim + embed. If a model OOMs at -ngl 99, lower it (e.g. flags=@('-ngl','24'))
    # until it fits. UNVALIDATED: no 8GB card in the authors' hardware; verify with llm bench.
    # Repo/path URLs need verification on huggingface.co before first use (llm fetch --list 8gb).
    '8gb' = @{
      _targetVRAM = '~8GB (ctx 4096, smaller quants) — NEEDS on-card validation'
      planner = @{ repo = 'Qwen/Qwen3-8B-GGUF';                       path = 'Qwen3-8B-Q4_K_M.gguf';                  gguf = 'qwen3-8b-q4_k_m.gguf';       ctx = 4096; kv = $true; sizeGB = 5.0; flags = @('--temp', '0.3') }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-7B-Instruct-GGUF'; path = 'Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf'; gguf = 'qwen-coder-7b-q4_k_m.gguf';  ctx = 4096; kv = $true; sizeGB = 4.7 }
      chat    = @{ repo = 'Qwen/Qwen3-4B-GGUF';                       path = 'Qwen3-4B-Q4_K_M.gguf';                  gguf = 'qwen3-4b-q4_k_m.gguf';       ctx = 4096; kv = $true; sizeGB = 2.6; setParams = @{ temperature = 0.7; top_p = 0.9 } }
      fim     = @{ repo = 'Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF';   path = 'qwen2.5-coder-1.5b-instruct-q8_0.gguf'; gguf = 'qwen-coder-1.5b-q8_0.gguf'; ctx = 2048; sizeGB = 1.9; ttl = 0; pinned = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                     path = 'bge-m3-Q8_0.gguf';                      gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true }
    }

    # Smaller quants + shorter context for ~12GB cards.
    # NOT VRAM-validated by the authors (no 12GB card here). A 12GB-card owner
    #    must confirm peak fit: resident big model + pinned fim + embed + KV + ctx.
    #    If a model OOMs at -ngl 99, add e.g. flags=@('-ngl','30') to spill layers to RAM.
    '12gb' = @{
      _targetVRAM = '~12GB (smaller quants, ctx 8192/4096) — NEEDS on-card validation'
      planner = @{ repo = 'Qwen/Qwen3-14B-GGUF';                      path = 'Qwen3-14B-Q4_K_M.gguf';                 gguf = 'qwen3-14b-q4_k_m.gguf';      ctx = 8192; kv = $true; sizeGB = 8.4; flags = @('--temp', '0.3') }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-7B-Instruct-GGUF'; path = 'Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf'; gguf = 'qwen-coder-7b-q4_k_m.gguf';  ctx = 8192; kv = $true; sizeGB = 4.7 }
      chat    = @{ repo = 'Qwen/Qwen3-8B-GGUF';                       path = 'Qwen3-8B-Q4_K_M.gguf';                  gguf = 'qwen3-8b-q4_k_m.gguf';       ctx = 8192; kv = $true; sizeGB = 5.0; setParams = @{ temperature = 0.7; top_p = 0.9 } }
      fim     = @{ repo = 'Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF';    path = 'qwen2.5-coder-1.5b-instruct-q8_0.gguf'; gguf = 'qwen-coder-1.5b-q8_0.gguf'; ctx = 4096; sizeGB = 1.9; ttl = 0; pinned = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                      path = 'bge-m3-Q8_0.gguf';                      gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true }
    }
  }
}
