# =============================================================================
#  models.psd1 — THE single source of truth for model selection.
#
#  Both the downloader (scripts/fetch-models.ps1) and the runtime config
#  (config/llama-swap.yaml, GENERATED by scripts/gen-llama-swap.ps1) derive
#  from this file. Edit here once; both follow.
#
#  Loaded with Import-PowerShellDataFile (data-only / safe — no code runs).
#
#  ── CHANGING MODELS / VRAM ──────────────────────────────────────────────────
#  Low on VRAM? Set `activeProfile = '12gb'` below BEFORE running setup, or later:
#      llm profile 12gb           (persists + regenerates the runtime config)
#      setup.bat -Profile 12gb    (at setup time)
#  Peek a profile without switching or downloading:
#      llm fetch --list 12gb      (dry-run; lists files + sizes, pulls nothing)
#
#  Profiles available: '8gb', '12gb', '16gb' (default), '24gb', '32gb'. See _targetVRAM.
#
#  ── SCHEMA (per model) ──────────────────────────────────────────────────────
#    repo / path  : HuggingFace repo + file path  → download URL
#    gguf         : local filename in models/      → also the -m path at runtime
#    ctx          : context window (-c). Omit for embeddings.
#    sizeGB       : approx on-disk size (display + dry-run totals only)
#    kv=$true     : apply the KV-cache quant macro (${kv}). Big models only — small
#                   pinned models (fim/embed) skip it (negligible KV at their size).
#    flags        : extra llama-server flags (array). Appended last, so they can
#                   OVERRIDE the srv-macro defaults (e.g. @('-ngl','30') for low VRAM).
#    setParams    : server-side sampling enforcement → llama-swap filters.setParams
#    ttl=0        : never auto-unload (pinning)
#    pinned=$true : keep resident — excluded from the swap group (see `group`)
#    embedding    : adds --embedding, omits the KV-quant flags
#  Keys starting with '_' (e.g. _targetVRAM) are METADATA, not models — skipped
#  by the generator and the downloader.
#
#  All repo/path URLs below verified live on huggingface.co (HTTP 200) on 2026-06-24.
#  If you CHANGE a repo/path, re-check it — quant filenames vary by uploader and casing
#  matters. Quick check:  llm fetch --list <profile>  then HEAD the resolve URLs.
# =============================================================================
@{
  # The active profile. '$env:LLM_PROFILE' (if set) overrides this for one
  # invocation without rewriting the file.
  activeProfile = '16gb'

  # Tunable knobs. Values here are the defaults; copy config/user.psd1.example to
  # config/user.psd1 (gitignored) to override any of these without touching git-tracked files.
  # Re-run `llm gen` after editing user.psd1. Changes take effect on next `llm serve`.
  defaults = @{
    ngl         = 99                # GPU layers. Lower (e.g. 80) to CPU-offload if OOM.
    flashAttn   = $true             # Required for KV-cache quant. Set false for CPU-only.
    kvQuantK    = 'q8_0'            # Key cache quant (--cache-type-k). Works with flash-attn on all GPU generations.
                                    #   Pre-Blackwell (sm_75–89, RTX 20/30/40): q5_1 saves ~30% more VRAM, good fidelity.
                                    #   Blackwell (sm_120+, RTX 50): sub-q8_0 types regress with flash-attn; keep q8_0.
                                    #   Options: f16, bf16, q8_0, q5_1, q5_0, q4_1, q4_0, iq4_nl
    kvQuantV    = 'q8_0'            # Value cache quant (--cache-type-v). ~50% VRAM savings vs f16.
                                    #   Pre-Blackwell: q4_0 saves ~75% vs f16 with acceptable quality.
                                    #   Options: f16, bf16, q8_0, q5_1, q5_0, q4_1, q4_0, iq4_nl
    kvQuant     = ''                # Legacy: when non-empty, overrides kvQuantK and kvQuantV with same type.
                                    #   To disable KV quant entirely (required for Gemma models):
                                    #     set kvQuantK = '' AND kvQuantV = '' in user.psd1 instead.
    threads     = -1                # CPU threads for BLAS/prompt. -1 = auto.
    batch       = 512               # Logical batch size (-b). NOTE: value 512 emits no flag; llama.cpp
                                    #   then uses its own default of 2048. Set > 512 to override explicitly.
    ubatch      = 512               # Physical GPU batch size (-ub). Raise to 1024/2048 to reduce
                                    #   kernel-launch overhead on long prompts. Must be <= effective batch.
    parallel    = 1                 # Parallel request slots (-np). >1 for multi-user setups.
    noMmap      = $false            # Load model into heap RAM at startup (--no-mmap). Eliminates page
                                    #   faults on CPU-offloaded layers. Slower startup; smoother inference.
                                    #   WARNING: with llama-swap, startup cost is paid on EVERY eviction+reload
                                    #   (not just once). A 17 GB model = 3-30 s per swap depending on storage.
                                    #   Recommended when system RAM >= 2x largest model. Per-model override
                                    #   also supported (set noMmap = $true on individual model entries).
    mlockBig    = $false            # Apply --mlock to swap-group models (planner/coder/chat).
                                    #   Pins CPU-resident pages in physical RAM, preventing OS eviction.
                                    #   Windows: needs SeLockMemoryPrivilege (secpol.msc). Without it: no-op.
                                    #   Recommended only with noMmap = $true and 32+ GB free RAM.
    numa        = ''                # NUMA thread/memory strategy (--numa). Options:
                                    #   '' (disabled), 'isolate' (pin to starting NUMA node),
                                    #   'distribute' (spread across all nodes), 'numactl' (use numactl map).
                                    #   On 7950X3D: try 'isolate' (keeps threads on V-Cache CCD).
                                    #   Benchmark 'isolate' vs 'distribute' with llm bench.
    port        = 8080              # llama-swap API endpoint port.
    webuiPort   = 3000              # Open WebUI port.
    litellmPort = 8081              # LiteLLM proxy port (Module H).
    langfusePort = 3001             # Langfuse observability port (Module H).
    searxngPort = 8888              # SearXNG private search port (Module H).
    n8nPort     = 5678              # n8n workflow automation port (Module H).
    n8nTimezone = 'UTC'             # n8n schedule timezone (IANA, e.g. 'America/New_York'). Override in user.psd1.
    maxTokens      = 512              # Default max_tokens for `llm chat`.
    webuiSecret    = 'local-llm-dev' # Change before exposing WebUI on LAN.
    langfuseEnabled = $false          # Set $true in user.psd1 after `llm services start`; enables Langfuse callbacks in litellm.yaml.
  }

  # System prompts per role — written to Open WebUI DB by gen-webui.ps1 (runs on `llm gen`).
  # Also keep systemMessage in sync in config/continue/config.yaml (not auto-generated).
  # Omit a role or set '' to clear its system prompt.
  # Override per-machine in config/user.psd1: prompts = @{ chat = 'custom prompt' }
  prompts = @{
    coder   = 'You are a skilled software engineer. Be direct. No preambles.'
    chat    = 'Be concise. /no_think'
    # planner: intentionally empty — let Qwen3 thinking run freely
  }

  # llama-server command pieces — values generated by gen-llama-swap.ps1 from defaults above.
  # Do not edit these; they are overwritten at every `llm gen` / `llm serve`.
  macros = @{
    srv = ''   # Generated. Do not edit.
    kv  = ''   # Generated. Do not edit.
  }

  # Swap policy. members = ROLE names that share VRAM (only one resident at a time;
  # loading one evicts the others). Pinned models (fim/embed) are NOT listed here —
  # their ttl:0 keeps them alongside whichever big model is active.
  group = @{ name = 'ondemand'; swap = $true; members = @('planner', 'coder', 'chat') }

  # ── API Pro Models ───────────────────────────────────────────────────────────
  # Routes {role}-pro model names through litellm directly to external API providers.
  # All three roles (chat, coder, planner) currently use DeepSeek — one key covers all.
  # Multiple providers are supported; enable additional peers and set the relevant env var.
  # Override any field or individual role model in config/user.psd1 (see user.psd1.example).
  # Re-run `llm gen` after editing. No llama-swap restart needed.
  #
  # litellmPrefix controls how gen-litellm.ps1 formats the model string:
  #   'deepseek'   → model: deepseek/<pro-value>   (LiteLLM native — no platform fee)
  #   'openai'     → model: openai/<pro-value> + api_base (any OpenAI-compatible endpoint)
  #   'openrouter' → model: openrouter/<pro-value>  (LiteLLM native — 5.5% platform fee)
  # Default when litellmPrefix is absent: 'openai'.
  peers = @{
    deepseek = @{
      enabled       = $true
      proxy         = 'https://api.deepseek.com'
      apiKeyEnv     = 'DEEPSEEK_API_KEY'           # env var NAME — never the key value
      litellmPrefix = 'deepseek'
      # Each role is a hashtable with 'model' + optional 'maxTokens'.
      # String values are also accepted (backward compat with user.psd1 overrides).
      # Verify the current model ID at platform.deepseek.com — 'deepseek-chat' routes to latest.
      pro = @{
        chat    = @{ model = 'deepseek-chat';     maxTokens = 4096; systemPrompt = 'Be helpful and concise.' }
        planner = @{ model = 'deepseek-reasoner'; maxTokens = 8192 }  # no prompt — R1 reasons on its own
        coder   = @{ model = 'deepseek-chat';     maxTokens = 4096; systemPrompt = 'You are an expert software engineer. Be direct. No preambles.' }
      }
    }
    zhipu = @{
      enabled       = $false                       # disabled — all roles use deepseek; re-enable to route coder back here
      proxy         = 'https://open.bigmodel.cn/api/paas/v4'
      apiKeyEnv     = 'ZHIPU_API_KEY'
      litellmPrefix = 'openai'
      pro = @{
        coder = 'glm-4-flash'
      }
    }
  }

  profiles = @{

    # Verified set. Runs on a 16GB card (RTX 5080): one big model resident at a
    # time; the 30B-A3B planner uses light RAM offload (fast — only 3B active).
    '16gb' = @{
      _targetVRAM = '16GB+ (tested RTX 5080; 30B planner uses light RAM offload)'
      # noMmap=$true: eliminates CPU-offload page faults but costs a full 17.3 GB disk read on every llama-swap eviction+reload.
      planner = @{ repo = 'Qwen/Qwen3-30B-A3B-GGUF';                   path = 'Qwen3-30B-A3B-Q4_K_M.gguf';             gguf = 'qwen3-30b-a3b-q4.gguf';      ctx = 16384; kv = $true; sizeGB = 17.3; flags = @('--temp', '0.3'); tokenizer = 'Qwen/Qwen3-30B-A3B'; noMmap = $true }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-14B-Instruct-GGUF'; path = 'Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf'; gguf = 'qwen-coder-14b-q4_k_m.gguf'; ctx = 16384; kv = $true; sizeGB = 8.4; draftRole = 'fim'; tokenizer = 'Qwen/Qwen2.5-Coder-14B-Instruct' }
      chat    = @{ repo = 'Qwen/Qwen3-14B-GGUF';                       path = 'Qwen3-14B-Q4_K_M.gguf';                 gguf = 'qwen3-14b-q4_k_m.gguf';      ctx = 16384; kv = $true; sizeGB = 8.4; setParams = @{ temperature = 0.7; top_p = 0.9 }; tokenizer = 'Qwen/Qwen3-14B' }
      fim     = @{ repo = 'Qwen/Qwen2.5-Coder-3B-Instruct-GGUF';       path = 'qwen2.5-coder-3b-instruct-q8_0.gguf';   gguf = 'qwen-coder-3b-q8_0.gguf';    ctx = 8192;  sizeGB = 3.4; ttl = 0; pinned = $true; mlock = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                      path = 'bge-m3-Q8_0.gguf';                      gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true; mlock = $true }
    }

    # Better quants for RTX 3090 / 4090 / 4080 Super (24 GB). Q5_K_M planner + Q6_K coder/chat.
    # Still swaps big models. UNVALIDATED: no 24GB card in authors' hardware — verify with llm bench.
    # Repo/path URLs need verification on huggingface.co before first use (llm fetch --list 24gb).
    '24gb' = @{
      _targetVRAM = '~24GB (RTX 3090 / 4090 / 4080 Super) — NEEDS on-card validation'
      _notes      = 'Q5_K_M planner (~21.3 GB), Q6_K coder/chat (~10.7 GB). Swaps big models as usual.'
      planner = @{ repo = 'bartowski/Qwen3-30B-A3B-GGUF';                   path = 'Qwen3-30B-A3B-Q5_K_M.gguf';            gguf = 'qwen3-30b-a3b-q5_k_m.gguf';  ctx = 16384; kv = $true; sizeGB = 21.3; flags = @('--temp', '0.3'); tokenizer = 'Qwen/Qwen3-30B-A3B' }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-14B-Instruct-GGUF';      path = 'Qwen2.5-Coder-14B-Instruct-Q6_K.gguf'; gguf = 'qwen-coder-14b-q6_k.gguf';   ctx = 16384; kv = $true; sizeGB = 10.7; draftRole = 'fim'; tokenizer = 'Qwen/Qwen2.5-Coder-14B-Instruct' }
      chat    = @{ repo = 'bartowski/Qwen3-14B-GGUF';                       path = 'Qwen3-14B-Q6_K.gguf';                  gguf = 'qwen3-14b-q6_k.gguf';        ctx = 16384; kv = $true; sizeGB = 10.7; setParams = @{ temperature = 0.7; top_p = 0.9 }; tokenizer = 'Qwen/Qwen3-14B' }
      fim     = @{ repo = 'bartowski/Qwen2.5-Coder-3B-Instruct-GGUF';       path = 'Qwen2.5-Coder-3B-Instruct-Q8_0.gguf';  gguf = 'qwen-coder-3b-q8_0.gguf';    ctx = 8192;  sizeGB = 3.4; ttl = 0; pinned = $true; mlock = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                           path = 'bge-m3-Q8_0.gguf';                     gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true; mlock = $true }
    }

    # Near-lossless quants for 32+ GB cards (RTX 5090, A6000, etc.). Still swaps big models
    # — planner alone is 24.2 GB; all three = 54 GB. True no-swap requires 48GB+ VRAM.
    # UNVALIDATED: verify with llm bench. If planner OOMs, lower ctx or add '-ngl' flag.
    # Repo/path URLs need verification on huggingface.co before first use (llm fetch --list 32gb).
    '32gb' = @{
      _targetVRAM = '~32GB (RTX 5090 / A6000 / high-VRAM cards) — NEEDS on-card validation'
      _notes      = 'Near-lossless quants (Q6_K planner ~24 GB, Q8_0 coder/chat ~15 GB). Swaps big models. 48GB+ for true no-swap.'
      planner = @{ repo = 'bartowski/Qwen3-30B-A3B-GGUF';                   path = 'Qwen3-30B-A3B-Q6_K.gguf';              gguf = 'qwen3-30b-a3b-q6_k.gguf';    ctx = 32768; kv = $true; sizeGB = 24.2; flags = @('--temp', '0.3'); tokenizer = 'Qwen/Qwen3-30B-A3B' }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-14B-Instruct-GGUF';      path = 'Qwen2.5-Coder-14B-Instruct-Q8_0.gguf'; gguf = 'qwen-coder-14b-q8_0.gguf';   ctx = 32768; kv = $true; sizeGB = 15.0; draftRole = 'fim'; tokenizer = 'Qwen/Qwen2.5-Coder-14B-Instruct' }
      chat    = @{ repo = 'bartowski/Qwen3-14B-GGUF';                       path = 'Qwen3-14B-Q8_0.gguf';                  gguf = 'qwen3-14b-q8_0.gguf';        ctx = 32768; kv = $true; sizeGB = 15.0; setParams = @{ temperature = 0.7; top_p = 0.9 }; tokenizer = 'Qwen/Qwen3-14B' }
      fim     = @{ repo = 'bartowski/Qwen2.5-Coder-3B-Instruct-GGUF';       path = 'Qwen2.5-Coder-3B-Instruct-Q8_0.gguf';  gguf = 'qwen-coder-3b-q8_0.gguf';    ctx = 8192;  sizeGB = 3.4; ttl = 0; pinned = $true; mlock = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                           path = 'bge-m3-Q8_0.gguf';                     gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true; mlock = $true }
    }

    # Tight fit for ~8GB cards (RTX 3070, 4060, etc.). One big model at a time alongside
    # pinned fim + embed. If a model OOMs at -ngl 99, lower it (e.g. flags=@('-ngl','24'))
    # until it fits. UNVALIDATED: no 8GB card in the authors' hardware; verify with llm bench.
    # Repo/path URLs need verification on huggingface.co before first use (llm fetch --list 8gb).
    '8gb' = @{
      _targetVRAM = '~8GB (ctx 4096, smaller quants) — NEEDS on-card validation'
      planner = @{ repo = 'Qwen/Qwen3-8B-GGUF';                       path = 'Qwen3-8B-Q4_K_M.gguf';                  gguf = 'qwen3-8b-q4_k_m.gguf';       ctx = 4096; kv = $true; sizeGB = 5.0; flags = @('--temp', '0.3'); tokenizer = 'Qwen/Qwen3-8B' }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-7B-Instruct-GGUF'; path = 'Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf'; gguf = 'qwen-coder-7b-q4_k_m.gguf';  ctx = 4096; kv = $true; sizeGB = 4.7; draftRole = 'fim'; tokenizer = 'Qwen/Qwen2.5-Coder-7B-Instruct' }
      chat    = @{ repo = 'Qwen/Qwen3-4B-GGUF';                       path = 'Qwen3-4B-Q4_K_M.gguf';                  gguf = 'qwen3-4b-q4_k_m.gguf';       ctx = 4096; kv = $true; sizeGB = 2.6; setParams = @{ temperature = 0.7; top_p = 0.9 }; tokenizer = 'Qwen/Qwen3-4B' }
      fim     = @{ repo = 'Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF';   path = 'qwen2.5-coder-1.5b-instruct-q8_0.gguf'; gguf = 'qwen-coder-1.5b-q8_0.gguf'; ctx = 2048; sizeGB = 1.9; ttl = 0; pinned = $true; mlock = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                     path = 'bge-m3-Q8_0.gguf';                      gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true; mlock = $true }
    }

    # Smaller quants + shorter context for ~12GB cards.
    # NOT VRAM-validated by the authors (no 12GB card here). A 12GB-card owner
    #    must confirm peak fit: resident big model + pinned fim + embed + KV + ctx.
    #    If a model OOMs at -ngl 99, add e.g. flags=@('-ngl','30') to spill layers to RAM.
    '12gb' = @{
      _targetVRAM = '~12GB (smaller quants, ctx 8192/4096) — NEEDS on-card validation'
      planner = @{ repo = 'Qwen/Qwen3-14B-GGUF';                      path = 'Qwen3-14B-Q4_K_M.gguf';                 gguf = 'qwen3-14b-q4_k_m.gguf';      ctx = 8192; kv = $true; sizeGB = 8.4; flags = @('--temp', '0.3'); tokenizer = 'Qwen/Qwen3-14B' }
      coder   = @{ repo = 'bartowski/Qwen2.5-Coder-7B-Instruct-GGUF'; path = 'Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf'; gguf = 'qwen-coder-7b-q4_k_m.gguf';  ctx = 8192; kv = $true; sizeGB = 4.7; draftRole = 'fim'; tokenizer = 'Qwen/Qwen2.5-Coder-7B-Instruct' }
      chat    = @{ repo = 'Qwen/Qwen3-8B-GGUF';                       path = 'Qwen3-8B-Q4_K_M.gguf';                  gguf = 'qwen3-8b-q4_k_m.gguf';       ctx = 8192; kv = $true; sizeGB = 5.0; setParams = @{ temperature = 0.7; top_p = 0.9 }; tokenizer = 'Qwen/Qwen3-8B' }
      fim     = @{ repo = 'Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF';    path = 'qwen2.5-coder-1.5b-instruct-q8_0.gguf'; gguf = 'qwen-coder-1.5b-q8_0.gguf'; ctx = 4096; sizeGB = 1.9; ttl = 0; pinned = $true; mlock = $true }
      embed   = @{ repo = 'gpustack/bge-m3-GGUF';                      path = 'bge-m3-Q8_0.gguf';                      gguf = 'bge-m3-q8_0.gguf';           sizeGB = 0.6; embedding = $true; ttl = 0; pinned = $true; mlock = $true }
    }
  }
}
