"""Shared Bob Python core: config, LLM client, memory access.

Import this in any Bob Python script instead of duplicating config loading
or calling bob_memory.py via subprocess.

Usage:
    from bob_core import load_config, get_llm_client, memory_recall, memory_store
"""
import json
import sys
from pathlib import Path
from typing import Optional

REPO = Path(__file__).parent.parent


def load_config() -> dict:
    """Load merged bob config from data/config.json (auto-generated by Get-BobConfig).

    Raises FileNotFoundError if config.json doesn't exist yet — run any `bob`
    command to generate it.
    """
    path = REPO / "data" / "config.json"
    if not path.exists():
        raise FileNotFoundError(
            f"data/config.json not found at {path}\n"
            "Run any `bob` command first to generate it (e.g. `bob status`)."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _litellm_key(config: dict) -> str:
    """Return the LiteLLM master key from config, defaulting to sk-local."""
    return config.get("litellmKey", "sk-local")


def get_llm_client(config: Optional[dict] = None):
    """Return an OpenAI client pointed at the LiteLLM proxy."""
    from openai import OpenAI

    cfg = config or load_config()
    port = cfg.get("litellmPort", 8081)
    return OpenAI(base_url=f"http://localhost:{port}/v1", api_key=_litellm_key(cfg))


def check_litellm(config: Optional[dict] = None) -> bool:
    """Return True if the LiteLLM proxy port is open (TCP connect; avoids slow /health backend checks)."""
    import socket

    cfg = config or load_config()
    port = int(cfg.get("litellmPort", 8081))
    try:
        with socket.create_connection(("localhost", port), timeout=3):
            return True
    except OSError:
        return False


def _get_db_path(config: Optional[dict] = None) -> str:
    cfg = config or load_config()
    rel = cfg.get("memory", {}).get("dbPath", "data\\bob.db")
    return str(REPO / rel.replace("\\", "/"))


def memory_store(content: str, tags: str = "", config: Optional[dict] = None) -> str:
    """Store content in bob.db directly (no subprocess)."""
    cfg = config or load_config()
    db_path = _get_db_path(cfg)
    _ensure_memory_importable()
    import bob_memory  # type: ignore

    bob_memory.store(content, db_path=db_path)
    return f"Stored: {content[:80]}"


def memory_recall(query: str, k: int = 5, config: Optional[dict] = None) -> str:
    """Recall top-k results from bob.db. Returns newline-joined content strings."""
    cfg = config or load_config()
    db_path = _get_db_path(cfg)
    _ensure_memory_importable()
    import bob_memory  # type: ignore

    results = bob_memory.recall(query, k=k, db_path=db_path)
    if not results:
        return "(no results)"
    return "\n".join(r["content"] for r in results)


def _ensure_memory_importable() -> None:
    scripts_dir = str(REPO / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
